server:
  port: 8870
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://127.0.0.1:8200
        instance:
          name: admin-cyy
          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
